### ISSUE TITLE
Incorrect link in SetupS-files.htm 

### ISSUE THREAD

**Issue by bphlpt** [pacav69/SetupS.Project_DevelopersPack#10]
@Glenn's comment -

--------------------------
ssWPI update package (.7z). A slightly modified ppApp-type package for integration with the ssWPI or ssGooey project(s). Simply copy it to the ssWPI folder, extract "here", then delete it.
SetupS.Uninstaller_v24.05.22.0.exe [(mirror1)](http://www.lastos.org/files/SetupS.Uninstaller_v24.05.22.0.exe) [(mirror2)](http://sstek.vergitek.com/blob/SetupS.Uninstaller_v24.05.22.0.exe) [(mirror3 right click on file to download)](http://github.com/pacav69/SetupS.Project_DevelopersPack/tree/main/files/)

All the mirrors for ssWPI update package (.7z). and the file descriptor say SetupS.Uninstaller_v24.05.22.0.exe <- so there is an issue with the Batch file that generates the html file.
--------------------------

refers to needed corrections in SetupS-files.htm to fix the link at https://www.lastos.org/files/SetupS-files.htm

That label and those 3 links all refer to SetupS.Uninstaller, while they should refer to the ssWPI update package, ie SetupS_v24.05.22.0_ssWPI.Update.Package.7z is the latest one I see.

Please correct the error in SetupS-files.htm and/or the batch file that generates it.

**Comment by pacav69** [comment]
you mean that 
ssWPI update package (.7z). 

SetupS.Uninstaller_v24.05.22.0.exe [(mirror1)](http://www.lastos.org/files/SetupS.Uninstaller_v24.05.22.0.exe) [(mirror2)](http://sstek.vergitek.com/blob/SetupS.Uninstaller_v24.05.22.0.exe) [(mirror3 right click on file to download)](http://github.com/pacav69/SetupS.Project_DevelopersPack/tree/main/files/) 

is pointing to the wrong file?

**Comment by pacav69** [comment]
corrected error in SetupS-files.htm to point to SetupS_v#ProjectVersion#_ssWPI.Update.Package.7z 
under the heading ssWPI update package (.7z)
